- name: System up to date
  hosts: localhost
  vars:
    reboot_controller: yes # since we're targeting localhost, make it reboot even if it is the controller
  roles:
  - role: system_up_to_date
    sub_task: sync_repo
  - role: system_up_to_date
    sub_task: setup_schedule
  - role: system_up_to_date
