on:
  push:
    branches:
      - main
    paths-ignore:
      - roles/**
  workflow_dispatch:
  # schedule: - gonna try using github rest api to triggero on upstream changes
  #     - cron: '30 1 * * *'

jobs:
  fetch_role:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Move role to correct folder
        run: |
          git clone https://github.com/mshafer1/ansible-configs.git /tmp/ansible-configs
          tree /tmp/ansible-configs
          rm -rf ./roles/system_up_to_date
          mv /tmp/ansible-configs/playbooks/roles/system_up_to_date ./roles/
          tree
      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: Update data file(s)
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -am "Update system update role from mshafer1/ansible-configs - ${{ github.sha }}" || exit 0
          git push
