on:
  push:
    branches:
      - main
    paths-ignore:
      - roles/**
  workflow_dispatch:
  schedule:
      - cron: '30 1 * * *'

jobs:
  fetch_role:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Move role to correct folder
        run: |
          git clone https://github.com/mshafer1/ansible-configs.git /tmp/ansible-configs
          tree /tmp/ansible-configs
          rm -rf ./roles/system_up_to_date
          mv /tmp/ansible-configs/playbooks/roles/system_up_to_date ./roles/
          tree
